"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$cmd_duration\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[character]
success_symbol = '[->](bold green)'
error_symbol = '[->](bold red)'
vimcmd_symbol = "[=>](bold blue)"
vimcmd_visual_symbol = "[=>](bold purple)"
vimcmd_replace_symbol = "[->](bold purple)"
vimcmd_replace_one_symbol = "[->](bold purple)"

[package]
format = "version\\([$version]($style)\\) "
style = "cyan"
disabled = false

[battery]
disabled = true

[cmd_duration]
format = "[$duration]($style) "

[rust]
format = "rust\\([$version]($style)\\) "
style = "cyan"

[nodejs]
format = "node(\\([$version]($style)\\)) "
style = "cyan"

[git_branch]
format = "git\\([$branch(:$remote_branch)](cyan)\\) "

[git_state]
format = "\\([$state( $progress_current/$progress_total)]($style)\\) "
disabled = true

[git_status]
disabled = false
style = "green"

modified = "~${count} "
staged = "+${count} "
deleted = "-${count} "
renamed = "*${count} "
stashed = "\\$${count} "
untracked = "?${count} "
ahead = '+${count}'
diverged = '+${ahead_count}-${behind_count}'
behind = '-${count}'

format = """
(\
[$modified](blue)\
[$staged](green)\
[$deleted](red)\
[$renamed](blue)\
[$stashed](purple)\
[$untracked](bright-red)\
)\
({[$ahead_behind](purple)} )\
"""
